
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfamntxdugxpxvgzajfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmYW1udHhkdWd4cHh2Z3phamZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MjgyMzEsImV4cCI6MjA2MzIwNDIzMX0.3aiGov64iqv0EKnYDD6wcrtaCruwaC_fMJvXGaPDErM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
